<?php
require_once("header.php");
?>
<p>You likely have several questions about all this. I will do my best to answer you here.</p>
<p>(If you have a question that isn't answered here, try <a href="http://the-overseer.wikia.com/wiki/FAQ" target="_blank">the Overseer Wiki FAQ</a>)</p>
<p><strong>Q: Who are you?</strong></p>
<p>A:You may refer to me as The Overseer.</p>
<p><strong>Q: What's going on here?</strong></p>
<p>A: The short answer is that I am attempting to create and expand a new multiverse, distinct from the suffering and tragedy that mark the one I left.</p>
<p><strong>Q: How?</strong></p>
<p>A: By borrowing sessions of the universal propagation tool likely known to you as Sburb, I intend to rebuild all of existence from scratch. Hopefully it will turn out better this time.</p>
<p><strong>Q: Why isn't my alchemy working?</strong></p>
<p>A: Part of the rebuild involves resetting the universal processes that allow for what you interface with as alchemy. This means that most of the combinations don't actually map to anything in the new multiverse you are now a part of. I will be creating every code by hand with the assistance of the players: you will submit suggestions for both specific codes and items that need to be in the system somewhere and I will bind the codes to the items, allowing their alchemization. Note that some existing combinations already exist. To get started with alchemy, you will need to access the catalogue for items to begin experimenting with.</p>
<p><strong>Q: This is boring!</strong></p>
<p>A: My systems are designed to track only the bare, mechanical basics of my new multiverse: items that exist, grist generated, things like that. The finer details are to be shaped by you, the players. That means detailing what activities you and your allies are up to, describing Lands, that sort of thing. Simply living. Each additional piece of data makes the resulting reality more complete. If you find that your actions have no context and that boredom is the result, try creating a context for them.</p>
<p><strong>Q: What's the deal with sessions?</strong></p>
<p>A: A session may be created at any time. Any player who enters their Medium must provide an existing session name and the session's corresponding password, placing them as a player of that session.</p>
<p><strong>Q: What about server and client connections?</strong></p>
<p>A: Each player may register a client who is in the same session as them. Once a loop of players is completed, it is still possible for other players to enter the session, however they will need to construct a second loop in order to play properly.</p>
<p><strong>Q: How does the prototyping work?</strong></p>
<p>A: You specify a single number pre-entry defining how powerful the item you are prototyping is. This is on a linear scale from -999 to 999 inclusive, with 999 representing the power of one of the original multiverse's First Guardians. There is a random chance of any enemy you encounter receiving your particular prototype, in which case it receives a power boost (or penalty) according to how powerful your prototyping is, so exercise caution. Your sprite will be twice as powerful as the prototyping power used on it, so use this to your advantage. A prototyping power level between 0 and 10 is generally your safest bet. Any enemy that benefits from multiple prototypings will have the benefits of all prototypings it receives multiplied together, so higher numbers will prove to be far riskier, even with the additional sprite power you receive.</p>
<p><strong>Q: How am I supposed to fight things?</strong></p>
<p>A: There are but two combat stats: power and health. Power is used for both damage dealt and taken, but is modified by the combat commands you choose. You may wield two average-sized weapons or one two-handed one, with a weapon in your off-hand only granting half bonuses. Your total power is the sum of your weapon power, your current height on your personal Echeladder, and the power of your sprite. I have taken the liberty of enabling sprites to travel with you at all times to reduce complications in this matter and increase your chances of success.</p>
<p>Each round of combat represents a decent amount of time spent fighting. You select two commands: an active one, and a passive one. The active commands are sorted in order of offensive power, and the passive ones in order of defensive power. The more offensive a command is, the less defensive it is, and vice versa. It is impossible for a single foe to deal more than 1/3 of your maximum health in a single round, so when fighting new enemies, make sure you test yourself against a single one first for safety. You may go looking for specific enemies whenever you like, with the only restriction being the fact that you can only fight enemies that can be found in your session.</p>
<p><strong>Q: What about weapons?</strong></p>
<p>A: Each weapon has a kind associated with it. If you equip one for which you do not have the correct abstratus and you have an abstratus unassigned, it will be automatically assigned to the correct abstratus to allow the equip. If you do not have a spare abstratus, you won't be given the option to equip new kinds.</p>
<p><strong>Q: What is a grist category and why do I care about it?</strong></p>
<p>A: Your grist category determines which types of grist form the enemies on your Land. The grist types of everyone in your session will determine the types of grist available to your entire session without attempting to barter grist with other sessions, which will in turn determine what items you are able to produce.</p>
<p><strong>Q: How does the Echeladder work?</strong></p>
<p>A: You gain one rung per successful combat. Simple, really. You can go and beat up weak enemies for easy rungs if you really want to, but beware that you will find yourself grist-starved compared to other players of comparable level and therefore weaker due to possessing less effective equipment.</p>
<?php require_once("footer.php"); ?>