<?php
require_once("header.php");
?>
<p>Alchemy is the process of combining any two items to make something new, unique, and usually more powerful. Any two items can be combined, as long as their codes interact.</p><br />
<p>If you have any questions about alchemy that aren't answered by this page, the <a href="http://the-overseer.wikia.com/wiki/Alchemy">Alchemy page on the Wiki</a> attempts to cover anything else.</p><br />
<p><strong>Non-canon Alchemy</strong></p><br />
<p>If you are in a non-canon session, alchemy is relatively simple. At the top of the inventory page, you'll find two Punch Designix forms that accept two inputs. The first form takes two codes input manually, and the second allows you to select inventory items from a dropdown menu. If either of these forms are used, the game will charge 4 build grist and output the code that they make when combined using the selected operation.</p><br />
<p>This code can then be plugged into either the Holopad or the Alchemiter, the two forms below the Designix. The Holopad will display the item name, description, and grist cost. The Alchemiter will attempt to create the item corresponding to the code, consuming the required grist and adding it to your inventory.</p><br />
<p>Note that not all combinations exist at present. If you stumble across a code that does not correspond to an item yet, you may suggest one using the Feedback/Submit page under the About menu. A moderator will review your item as soon as they can, and once it is approved, it will be added to the game.</p><br />
<p><strong>Canon Alchemy</strong></p><br />
<p>If you're playing in a canon session, the alchemy process mimics that of the canonical game of SBURB.</p><br />
<p>The first thing you will need is some blank Captchalogue Cards. Your server player can deploy them into your storage for now. Ensure that you have at least one blank card in your inventory and visit the SBURB Devices page under the Player menu. Make sure your server has deployed the four necessary machines required for alchemy: the Punch Designix, the Cruxtruder, the Totem Lathe, and the Alchemiter.</p><br />
<p>Your first stop is the Punch Designix menu at the very top. The dropdown menu contains all of the captchalogue cards in your inventory. Select the one you wish to punch, and input the code to punch it with in the field below. The card that you punch does not have to be blank; punching a card with a code already on it will combine that code with the new code using the operation || (OR).</p><br />
<p>Next is the Cruxtruder. You will need at least one blank Cruxite Dowel to carve the code into. Input the desired quantity and select either Sylladex (inventory) or Storage. You will extract that amount of Cruxite Dowels into the chosen location. This process is free.</p><br />
<p>When you have a punched card and a blank dowel, the Totem Lathe is the next machine to use. You can select one or two Captchalogue Cards to insert into the Lathe. Inserting two cards will combine the two codes using the operation && (AND). It will automatically consume a blank Cruxite Dowel from your inventory and carve it into a totem with the new code.</p><br />
<p>Finally, take your carved totem to the Alchemiter. Simply select a carved totem and a quantity, and the Alchemiter will scan the totem and attempt to produce that many of the corresponding item. Note that if you lack the required grist, you will see only the grist cost, with the missing grists in red.</p><br />
<p>You can use the canon devices in a non-canon session if you're really curious. Likewise, a canon session can use the non-canon devices, but this requires alchemizing an upgrade.</p>
<?php require_once("footer.php"); ?>